/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package principal;

/**
 *
 * @author Leandro
 */
public class jpFormulario1 extends javax.swing.JPanel {

    /**
     * Creates new form jpFormulario1
     */
    public jpFormulario1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtRadioC = new javax.swing.JTextField();
        lblRadio = new javax.swing.JLabel();
        lblAreaC = new javax.swing.JLabel();
        txtAreaC = new javax.swing.JTextField();
        lblPerimetroC = new javax.swing.JLabel();
        txtPerimetroC = new javax.swing.JTextField();
        btnCalcular1 = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        txtRadioC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRadioCActionPerformed(evt);
            }
        });

        lblRadio.setText("Radio");

        lblAreaC.setText("Area");

        txtAreaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAreaCActionPerformed(evt);
            }
        });

        lblPerimetroC.setText("Perimetro");

        txtPerimetroC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPerimetroCActionPerformed(evt);
            }
        });

        btnCalcular1.setText("Calcular");
        btnCalcular1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcular1ActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRadio)
                    .addComponent(lblAreaC)
                    .addComponent(lblPerimetroC)
                    .addComponent(btnCalcular1))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLimpiar)
                    .addComponent(txtPerimetroC, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRadioC, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAreaC, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(373, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRadio)
                    .addComponent(txtRadioC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblAreaC)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAreaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPerimetroC, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPerimetroC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular1)
                    .addComponent(btnLimpiar))
                .addContainerGap(442, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtRadioCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRadioCActionPerformed

    }//GEN-LAST:event_txtRadioCActionPerformed

    private void txtPerimetroCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPerimetroCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPerimetroCActionPerformed

    private void btnCalcular1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcular1ActionPerformed
        double A,B ;
        
        double radio = Double.parseDouble(txtRadioC.getText());

        Circulo circulo= new Circulo(radio);
        A=circulo.calcularArea();
        B=circulo.calcularPerimetro();
        txtAreaC.setText(String.valueOf(A));
        txtPerimetroC.setText(String.valueOf(B));
    }//GEN-LAST:event_btnCalcular1ActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtAreaC.setText(Circulo.Limpiar());
        txtPerimetroC.setText(Circulo.Limpiar());
        txtRadioC.setText(Circulo.Limpiar());



    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtAreaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAreaCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAreaCActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular1;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel lblAreaC;
    private javax.swing.JLabel lblPerimetroC;
    private javax.swing.JLabel lblRadio;
    private javax.swing.JTextField txtAreaC;
    private javax.swing.JTextField txtPerimetroC;
    private javax.swing.JTextField txtRadioC;
    // End of variables declaration//GEN-END:variables
}
